name: coverage
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Generate code coverage
      env:
        DISSONANCE_IT_TOKEN: ${{secrets.DISSONANCE_IT_TOKEN}}
      run: sbt ++2.13.5 'project core' clean coverage test coverageReport
    - name: Upload coverage
      uses: codecov/codecov-action@v1
